### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by sterlingbaldwin** [pacificclimate/esgf_download#4]
Hey guys, Im working on a project for ACME that has to download ESGF files and found your project. It would be extremely useful to me if I could get it up and running! Would it be possible to get a usage example of how to add files to the download queue? Thanks!

**Comment by basilveerman** [comment]
Thanks for your interest!

Was there any step in particular you were having troubles with in the [Readme](https://github.com/pacificclimate/esgf_download#usage)? I've just gone through a re-install and didn't have any new issues, but I may not be accounting for system discrepancies.

To be honest, we developed this pretty much for in house use. If you'd like to use it, that's great, but I must warn you: there will be dragons :). I'd recommend checking out [Synda](https://github.com/Prodiguer/synda) if you're looking for something that may be better supported.

**Comment by sterlingbaldwin** [comment]
Thanks! Im fairly new to the ESGF ecosystem and looking around for something to help me download datasets programmatically. From a brief examination of Synda, it might be what Im looking for.
